2024-05-31 13:54:40.281 [info] 




2024-05-31 13:54:40.299 [info] Extension host agent started.
2024-05-31 13:54:40.384 [info] [<unknown>][94dbc0e0][ManagementConnection] New connection established.
2024-05-31 13:54:40.403 [info] [<unknown>][a6cacf76][ExtensionHostConnection] New connection established.
2024-05-31 13:54:40.623 [info] [<unknown>][a6cacf76][ExtensionHostConnection] <47743> Launched Extension Host Process.
2024-05-31 13:54:50.525 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 13:54:50.541 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 13:55:09.871 [info] [<unknown>][53adbcaf][ExtensionHostConnection] New connection established.
2024-05-31 13:55:09.886 [info] [<unknown>][53adbcaf][ExtensionHostConnection] <48057> Launched Extension Host Process.
2024-05-31 13:55:09.888 [info] [<unknown>][d5e405f3][ManagementConnection] New connection established.
2024-05-31 13:58:49.149 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 13:58:49.288 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 13:58:49.290 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 13:58:49.291 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 13:59:40.299 [info] New EH opened, aborting shutdown
2024-05-31 14:06:38.925 [info] [<unknown>][a6cacf76][ExtensionHostConnection] <47743> Extension Host Process exited with code: 0, signal: null.
2024-05-31 14:06:38.927 [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/server/node/server.main.js:189:6057)
    at process.emit (node:events:517:28)
2024-05-31 15:13:14.336 [info] [<unknown>][6b0025ff][ManagementConnection] New connection established.
2024-05-31 15:13:14.339 [info] [<unknown>][5974ec32][ExtensionHostConnection] New connection established.
2024-05-31 15:13:14.352 [info] [<unknown>][5974ec32][ExtensionHostConnection] <52643> Launched Extension Host Process.
2024-05-31 15:13:31.253 [error] CodeExpectedError: Could not find pty on pty host
    at b.U (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:52:32991)
    at b.updateTitle (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:52:28152)
    at A.<computed> (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:52:23406)
    at Object.call (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5112)
    at a.s (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5118)
    at a.q (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4636)
    at n.value (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4045)
    at i.y (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:29:670)
    at i.fire (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:29:889)
    at process.$e (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:25:10159)
    at process.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-05-31 15:13:31.330 [error] CodeExpectedError: Could not find pty on pty host
    at b.U (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:52:32991)
    at b.updateIcon (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:52:28203)
    at A.<computed> (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:52:23406)
    at Object.call (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5112)
    at a.s (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5118)
    at a.q (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4636)
    at n.value (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4045)
    at i.y (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:29:670)
    at i.fire (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:29:889)
    at process.$e (/home/student/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/vs/platform/terminal/node/ptyHostMain.js:25:10159)
    at process.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-05-31 15:18:14.564 [info] [<unknown>][53adbcaf][ExtensionHostConnection] <48057> Extension Host Process exited with code: 0, signal: null.
2024-05-31 15:50:18.772 [info] [<unknown>][ea89f949][ManagementConnection] New connection established.
2024-05-31 15:50:18.784 [info] [<unknown>][b210aa95][ExtensionHostConnection] New connection established.
2024-05-31 15:50:18.798 [info] [<unknown>][b210aa95][ExtensionHostConnection] <56042> Launched Extension Host Process.
2024-05-31 15:50:35.352 [info] [<unknown>][ea89f949][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2024-05-31 15:50:37.154 [info] [<unknown>][27872d77][ExtensionHostConnection] New connection established.
2024-05-31 15:50:37.176 [info] [<unknown>][27872d77][ExtensionHostConnection] <56099> Launched Extension Host Process.
2024-05-31 15:50:37.179 [info] [<unknown>][f96c42a5][ManagementConnection] New connection established.
2024-05-31 15:55:37.356 [info] [<unknown>][b210aa95][ExtensionHostConnection] <56042> Extension Host Process exited with code: 0, signal: null.
2024-05-31 16:02:15.878 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:02:16.254 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:02:16.672 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:05:38.567 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:05:38.826 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:28:37.736 [warning] [File Watcher (node.js)] Watcher shutdown because watched path got deleted
2024-05-31 16:28:37.738 [warning] [File Watcher (node.js)] Watcher shutdown because watched path got deleted
2024-05-31 16:32:38.296 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:32:38.315 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:32:38.542 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:33:33.082 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 16:33:33.280 [error] AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1601:5)
2024-05-31 19:50:49.846 [info] [<unknown>][5974ec32][ExtensionHostConnection] <52643> Extension Host Process exited with code: 0, signal: null.
2024-05-31 19:57:06.109 [info] [<unknown>][27872d77][ExtensionHostConnection] <56099> Extension Host Process exited with code: 0, signal: null.
2024-05-31 19:57:06.109 [info] Last EH closed, waiting before shutting down
2024-05-31 20:02:06.111 [info] Last EH closed, shutting down
